### ISSUE TITLE
Permission reduction

### ISSUE THREAD

**Issue by JohnStrunk** [backube/volsync#363]
This issue tracks the work to reduce the permissions required by VolSync.

### Goals

- By default, both VolSync and the movers should run under the [Pod Security Standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/) "Restricted" policy
- It should be possible to securely enable VolSync to run movers with elevated privileges when necessary to preserve permissions/UID/GID during replication

### Tasks

- [ ] Modify the VolSync operator Deployment to comply with PSS/Restricted
- [ ] Provide a well-known annotation that can be added to the user's Namespace that indicates movers should run there with elevated permissions
- [ ] Create a new rsync-based mover that uses stunnel w/ PSK instead of ssh to protect the transfer.
- [ ] Deprecate the old rsync/ssh mover since we can't sufficiently reduce its permissions
- [ ] Rclone: enable reduced mover permissions
- [ ] Restic: enable reduced mover permissions
- [ ] Syncthing: enable reduced mover permissions
- [ ] CLI: Enhance CLI to support "migration" via rsync/stunnel

**Comment by tesshuflower** [comment]
Moving to version 0.8 milestone to cover cli enhancement and deprecating the rsync/ssh mover.
